const VAULT_FILE_EXT = '.pvault';
const BACKUP_FILE_EXT = '.pvault.bak';
const TEMP_FILE_EXT = '.pvault.tmp';
const PLAIN_EXPORT_EXT = '.json';
const ENCRYPTED_EXPORT_EXT = '.pvault';

const LANGUAGES = ['zh-CN', 'en-US'];
const THEMES = ['dark', 'light'];

const ERROR_LIMIT_OPTIONS = [3, 5, 7, 11, 99];
const DEFAULT_ERROR_LIMIT = 5;
const COOLDOWN_SECONDS = 30;

const AUTO_LOCK_OPTIONS = [5, 15, 30, 60, 120, 0];
const DEFAULT_AUTO_LOCK_MINUTES = 30;

const PASSWORD_REVEAL_OPTIONS = [3, 5, 10, 30, 0];
const DEFAULT_PASSWORD_REVEAL = 3;

const CLIPBOARD_CLEAR_OPTIONS = [1, 3, 5, 0];
const DEFAULT_CLIPBOARD_CLEAR = 1;

const KEY_MIN_LENGTH = 8;
const PASSWORD_MIN_LENGTH = 4;
const LONG_PRESS_MS = 300;

const VAULT_ID_PREFIX_STEP = 10000;

module.exports = {
  VAULT_FILE_EXT, BACKUP_FILE_EXT, TEMP_FILE_EXT,
  PLAIN_EXPORT_EXT, ENCRYPTED_EXPORT_EXT,
  LANGUAGES, THEMES,
  ERROR_LIMIT_OPTIONS, DEFAULT_ERROR_LIMIT, COOLDOWN_SECONDS,
  AUTO_LOCK_OPTIONS, DEFAULT_AUTO_LOCK_MINUTES,
  PASSWORD_REVEAL_OPTIONS, DEFAULT_PASSWORD_REVEAL,
  CLIPBOARD_CLEAR_OPTIONS, DEFAULT_CLIPBOARD_CLEAR,
  KEY_MIN_LENGTH, PASSWORD_MIN_LENGTH, LONG_PRESS_MS,
  VAULT_ID_PREFIX_STEP
};
